version: "3"
services:
  ms-feedbacksettings-sandbox:
    container_name: ms-feedbacksettings-sandbox
    image: 'ms-feedbacksettings:sandbox'
    network_mode: bridge
    links:
      - 'ms-feedbacksettings-db-sandbox:mariadb'
    restart: always
    build:
      context: ../../..
      dockerfile: ./src/main/docker/Dockerfile
    ports:
      - "8704:9090"
    environment:
      QUARKUS_PROFILE: 'sandbox'
      QUARKUS_DATASOURCE_JDBC_URL: 'jdbc:mariadb://mariadb:3306/sandbox-feedbacksettings'
      QUARKUS_DATASOURCE_USERNAME: 'sandbox-user'
      QUARKUS_DATASOURCE_PASSWORD: 'sandbox-password'
    depends_on:
      - ms-feedbacksettings-db-sandbox

  ms-feedbacksettings-db-sandbox:
    container_name: ms-feedbacksettings-db-sandbox
    image: 'mariadb:10.6.4'
    network_mode: bridge
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD : 'yes'
      MARIADB_DATABASE: 'sandbox-feedbacksettings'
      MARIADB_USER: 'sandbox-user'
      MARIADB_PASSWORD: 'sandbox-password'
    expose:
      - '3306'
      